### ISSUE TITLE
Fluffy on mac

### ISSUE THREAD

**Issue by thijskrijs** [FluffierThanThou/RelationsTab#1]
Hello,
I am trying to use this mod, but when I try to run it my game just don't work. I can't click on anything and I can't play the game. I have a mac, but I have used a lot of different mods wich are working fine. I have tried to run the mod only, but then I can't even select a world. I hope to hear from you.

With regards,
Thijs

**Comment by Pandaueen** [comment]
I also have the same issue but I am on Windows. I tried only this mod and the game shows like this ![relations](https://cloud.githubusercontent.com/assets/19619767/15625636/9a7e7124-24ae-11e6-91e3-06988c1ba5da.png) I can't click on anything, and it's paused even though i have the pause on load unchecked, the only thing i can do is press Esc key and it unpauses but i still can't click on anything not even the keyboard keys work. The mod looks neat i hope i will be able to use it :) at one point.
Br,
Angiel (ludeon)

**Comment by FluffierThanThou** [comment]
Sorry for the late response guys, but in future if you find a bug please attach the output_log.txt so I can see what's actually going on.
