### ISSUE TITLE
Null check VisibleInTab

### ISSUE THREAD

**Issue by FluffierThanThou** [FluffierThanThou/RelationsTab#14]
https://github.com/FluffierThanThou/RelationsTab/blob/0ffc8ba255040e6ad040015086aee0a828b24584/Source/Fluffy_Relations/RelationsHelper.cs#L29

https://steamcommunity.com/linkfilter/?url=https://gist.github.com/HugsLibRecordKeeper/0e48fb3164ede144b39e792e22a7fd18

**Comment by jamesamor** [comment]
Hi - Not sure if this is useful or not. I've got the same issue as this I think. Clicking the tab does nothing and there is a null reference exception being thrown with 'filename unknown'. I don't get the error on a new game with the same mod list.

Output File
http://pastebin.com/0hYcMemJ

Mod Config
http://pastebin.com/TiJEWrqJ

Save Game
https://www.dropbox.com/s/4wl0b78jun1svcc/Braselton%20%28Permadeath%29.rws?dl=0
