### ISSUE TITLE
Nullcheck for head graphic before drawing

### ISSUE THREAD

**Issue by erdelf** [FluffierThanThou/RelationsTab#16]
Not an issue with the mod itself, but modded races without heads cause problems when opening the relationtab.
A simple null check before drawing it should be enough.

**Comment by FluffierThanThou** [comment]
I'm going to commit something in a bit that should fix this, next time please add reproduction steps so I can check if it works (even if it's a simple fix, in this case I have no idea what specific part is actually null, so I had to assume it was `Pawn.Drawer.renderer.graphics.headGraphic` itself that can be null)
