### ISSUE TITLE
remember view type

### ISSUE THREAD

**Issue by Karel-Kroeze** [FluffierThanThou/RelationsTab#25]
Would it be possible for you to add an option in the mod settings to make the circle view the default view that comes up rather than the dynamic view? I find the circle view easier to work with, and it's fairly annoying to have to switch to it every time I open up the relations tab.

**Comment by FluffierThanThou** [comment]
I either already implemented this and forgot to close this ticket, or it has always functioned like this. Either way, closing the ticket.
