### ISSUE TITLE
Error with Relations Tab [HardcoreSK]

### ISSUE THREAD

**Issue by Rhyssia** [FluffierThanThou/RelationsTab#8]
Just getting this error. [HardcoreSK] Author says it is issue with RelationsTab not being able to draw non-vanilla texture.

![error](https://cloud.githubusercontent.com/assets/24862205/21696593/c63b6f44-d35c-11e6-8c03-b7eb5b932d0b.jpg)

**Comment by skyarkhangel** [comment]
Yep, its modded pawn from Skynet faction (Skynet SK mod in Hardcore SK), that change face texture.

**Comment by FluffierThanThou** [comment]
thanks for the report, I'll try to replicate. To be fair, if it is because of a custom faction, then it would be the author's responsibility to ensure that textures are available in the expected (vanilla) places.

I'll investigate and get back to you.

**Comment by FluffierThanThou** [comment]
has nothing to do with textures, the error is called from DrawDetails(), which draws the text on the left side of the screen. It was probably related to a faction with no leader, and unable to get a leader.
